name: Get Top Ten Deals

on:
  schedule:
    # 1230 AEST
    - cron: 30 2 * * *

jobs:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: Set up Python 3.10
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  - name: Run Module
    run: python -m QantasWineBonusPointsLister
