name: "Get Top Ten Deals"

on: [push]
#  schedule: 
#     - cron: "30 2 * * *"

jobs:
  once-a-day-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.10"
      - name: Setup date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Run everything
        run: |
          pip install -r requirements.txt
          echo '1'
          cp .github/README_template.md README.md
          echo '2'
          echo "Run on $CURRENT_DATE" >> README.md
          echo '3'
          echo '' >> README.md
          echo '4'
          python -m QantasWineBonusPointsLister -n >> README.md
          echo '5'
          echo '' >> README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "automatic update"
        env:
          CURRENT_DATE: ${{ steps.date.outputs.date }}
      - name: Checkin
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}      
